# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Foundries.io

# Persistence and directories
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information

# Basic security
allow_anonymous false
password_file /mosquitto/config/passwords

# MQTT TCP Listener
listener 1883
protocol mqtt

# WebSocket Listener (optional)
listener 9001
protocol websockets

