version: '3.6'

services:
  flutter-imx8-dev:
    image: hub.foundries.io/ew2022/flutter-imx8-dev:latest
    restart: always
    tty: true
    read_only: true
    network_mode: "host"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /run/user/63:/run/user/63
    - /dev/dri:/dev/dri
    - /dev/galcore:/dev/galcore
    device_cgroup_rules:
    - 'c 199:* rmw'
    - 'c 226:* rmw'