version: '3.2'

services:
  x-kiosk:
    image: hub.foundries.io/lmp/x-kiosk:latest
    restart: always
    privileged: true
    tty: true
    command: "--kiosk ${ADDR-foundries.io}"
    volumes:
      ./start.sh:/start.sh:ro
      ./xorg.conf:/etc/X11/xorg.conf:ro
